name: Flask Application CI/CD Pipeline

on:
  push:
    branches:
      - project-2-cicd

permissions:
  id-token: write
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      # 1. Download the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate GitHub Actions with AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::670412093221:role/GitHubActions-ECR-Role
          aws-region: us-east-2

      # 3. Login Docker to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build the Docker image
      - name: Build Docker image
        run: docker build -t flask-app .

      # 5. Tag the image for Amazon ECR
      - name: Tag Docker image
        run: docker tag flask-app:latest 670412093221.dkr.ecr.us-east-2.amazonaws.com/flask-app:latest

      # 6. Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push 670412093221.dkr.ecr.us-east-2.amazonaws.com/flask-app:latest

      # 7. Run the container for testing
      - name: Run container
        run: docker run -d -p 5000:5000 --name flask-test flask-app

      # 8. Give Flask time to start
      - name: Wait for app
        run: sleep 5

      # 9. Test the application
      - name: Test health endpoint
        run: curl http://localhost:5000/health

      # 10. Stop and remove the test container
      - name: Stop container
        run: docker stop flask-test && docker rm flask-test

      # 11. Deploy the new image to EC2 using AWS Systems Manager
      - name: Deploy to EC2 via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region us-east-2 \
            --instance-ids i-012fc62073822cd9b \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ubuntu/devops-project",
              "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 670412093221.dkr.ecr.us-east-2.amazonaws.com",
              "docker compose pull web",
              "docker compose up -d web"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --region us-east-2 \
            --command-id "$COMMAND_ID" \
            --instance-id i-012fc62073822cd9b

          echo "EC2 deployment completed successfully."
